name: Databricks CI/CD

on:
  push:
    branches:
      - dev
  release:
    types: [published]


env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  TESTS_DIRECTORY: tests
  REQUIREMENTS_PATH: tests/requirements.txt
  CLUSTER_CONFIG_PATH: tests/cluster.json
  DATABRICKS_REPO_PATH_DEVELOPMENT: dev
  DATABRICKS_REPO_PATH_STAGING: staging
  DATABRICKS_REPO_PATH_PRODUCTION: prod


jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Identify Repo Path
      id: path
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo REPO_PATH=${{ env.DATABRICKS_REPO_PATH_STAGING }} >> $GITHUB_OUTPUT
        else
          echo REPO_PATH=${{ env.DATABRICKS_REPO_PATH_DEVELOPMENT }} >> $GITHUB_OUTPUT
        fi

    - name: Create or Update Databricks Repo
      uses: ./.github/actions/repos
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        repo_url:  ${{ github.event.repository.url }}
        branch_or_tag: ${{ github.ref_name }}
        type_of_trigger: ${{ github.ref_type }}

    - name: Run Tests
      uses: ./.github/actions/jobs
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        folder_path: ${{ env.TESTS_DIRECTORY }}
        requirements_path: ${{ env.REQUIREMENTS_PATH }}
        cluster_config_path: ${{ env.CLUSTER_CONFIG_PATH }}

  Release:
    needs: [Push]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Create or Update Databricks Production Repo
      uses: ./.github/actions/repos
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ env.DATABRICKS_REPO_PATH_PRODUCTION }}/${{ github.event.repository.name }}
        repo_url:  ${{ github.event.repository.url }}
        branch_or_tag: ${{ github.ref_name }}
        type_of_trigger: ${{ github.ref_type }}
