name: Databricks CI/CD

on:
  push:
    branches:
      - dev
  release:
    types: [published]


env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  # Datatabricks Repo Paths
  DATABRICKS_REPO_PATH_DEVELOPMENT: dev
  DATABRICKS_REPO_PATH_STAGING: staging
  DATABRICKS_REPO_PATH_PRODUCTION: prod
  # Directories to run tests
  UNIT_TEST_DIR: tests/unit
  INTEGRATION_TEST_DIR: tests/integration
  REQUIREMENTS_FILE: requirements.txt
  CLUSTER_CONFIG_FILE: cluster.json
  # Booleans for running tests
  UNIT_TEST: false
  INTEGRATION_TEST: true
  INTEGRATION_TEST_WITH_DLT: true


jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Identify Repo Path
      id: path
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo REPO_PATH=${{ env.DATABRICKS_REPO_PATH_STAGING }} >> $GITHUB_OUTPUT
        else
          echo REPO_PATH=${{ env.DATABRICKS_REPO_PATH_DEVELOPMENT }} >> $GITHUB_OUTPUT
        fi

    - name: Create or Update Databricks Repo
      uses: ./.github/actions/repos
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        repo_url:  ${{ github.event.repository.url }}
        branch_or_tag: ${{ github.ref_name }}
        type_of_trigger: ${{ github.ref_type }}

    - name: Unit Test - Workflows
      if: ${{ env.UNIT_TEST == 'true' }}
      uses: ./.github/actions/jobs
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        name: "Testing: ${{ github.event.repository.name }} | ${{ github.ref_name }}"
        folder_path: ${{ env.UNIT_TEST_DIR }}
        requirements_path: "${{ env.UNIT_TEST_DIR }}/${{ env.REQUIREMENTS_FILE }}"
        cluster_config_path: "${{ env.UNIT_TEST_DIR }}/${{ env.CLUSTER_CONFIG_FILE }}"

    - name: Integration Test - Workflows
      if: ${{ env.INTEGRATION_TEST_WITH_DLT != 'true' && env.INTEGRATION_TEST == 'true' }}
      uses: ./.github/actions/jobs
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        name: "Testing: ${{ github.event.repository.name }} | ${{ github.ref_name }}"
        folder_path: "${{ env.INTEGRATION_TEST_DIR }}/${{ steps.path.outputs.REPO_PATH }}"
        requirements_path: "${{ env.INTEGRATION_TEST_DIR }}/${{ env.REQUIREMENTS_FILE }}"
        cluster_config_path: "${{ env.INTEGRATION_TEST_DIR }}/${{ env.CLUSTER_CONFIG_FILE }}"
  
    - name: Integration Test - DLT
      if: ${{ env.INTEGRATION_TEST_WITH_DLT == 'true' && env.INTEGRATION_TEST == 'true' }}
      uses: ./.github/actions/dlt
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ steps.path.outputs.REPO_PATH }}/${{ github.event.repository.name }}
        name: "Testing: ${{ github.event.repository.name }} | ${{ github.ref_name }}"
        folder_path: "${{ env.INTEGRATION_TEST_DIR }}/${{ steps.path.outputs.REPO_PATH }}"
        cluster_config_path: "${{ env.INTEGRATION_TEST_DIR }}/${{ env.CLUSTER_CONFIG_FILE }}"

  Release:
    needs: [Push]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Create or Update Databricks Production Repo
      uses: ./.github/actions/repos
      with:
        databricks_host: ${{ env.DATABRICKS_HOST }}
        databricks_token: ${{ env.DATABRICKS_TOKEN }}
        databricks_path: /Repos/${{ env.DATABRICKS_REPO_PATH_PRODUCTION }}/${{ github.event.repository.name }}
        repo_url:  ${{ github.event.repository.url }}
        branch_or_tag: ${{ github.ref_name }}
        type_of_trigger: ${{ github.ref_type }}
